// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';

export function GetAPIBaseURL():Promise<string>;

export function GetBasicAuthPassword():Promise<string>;

export function GetBasicAuthUser():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SetGinHandler(arg1:http.Handler):Promise<void>;
